_wandb:
    value:
        cli_version: 0.26.1
        e:
            tni5vmvop1s2la55l839ib8lzwoi7ik6:
                args:
                    - train
                    - -o
                    - /pscratch/sd/m/mbenyas/
                    - --save-tag
                    - fine_tune_qg_pretrain_l
                    - --pretrain-tag
                    - pretrain_l
                    - --fine-tune
                    - --dataset
                    - qg
                    - --mode
                    - classifier
                    - --num-classes
                    - "2"
                    - --path
                    - /global/cfs/cdirs/m4567/www/
                    - --size
                    - large
                    - --use-pid
                    - --interaction
                    - --batch
                    - "128"
                    - --epoch
                    - "15"
                    - --wd
                    - "10.0"
                    - --lr
                    - "1e-6"
                    - --num-workers
                    - "4"
                    - --wandb
                    - --resuming
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "134865891328"
                        used: "668467200"
                email: mbenyas@stanford.edu
                executable: /global/common/software/nersc9/pytorch/2.11.0/bin/python3.12
                git:
                    commit: 6dee75bb9b0b632231f982c3d3e203b9c8c3e8e1
                    remote: https://github.com/wamorkart/OmniLearned.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-ca45ed3d-de07-7606-7c31-f941b2519c6b
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-daf2aa4d-59aa-4def-ae0d-9ac95e15e0e6
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-7e7f6934-11ba-7156-a8a2-21ac658c1a3a
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-175dce3d-5472-db28-818d-b34e3056d2a1
                host: nid001417
                memory:
                    total: "269731786752"
                os: Linux-6.4.0-150600.23.103_15.0.25-cray_shasta_c-x86_64-with-glibc2.38
                program: /global/homes/m/mbenyas/.local/perlmutter/pytorch2.11.0/bin/omnilearned
                python: CPython 3.12.13
                root: /global/cfs/cdirs/m3246/mbenyas/OmniLearned_distillation
                slurm:
                    cluster_name: perlmutter
                    cpu_bind: quiet,mask_cpu:0x000000000000FFFF000000000000FFFF,0x00000000FFFF000000000000FFFF0000,0x0000FFFF000000000000FFFF00000000,0xFFFF000000000000FFFF000000000000
                    cpu_bind_list: 0x000000000000FFFF000000000000FFFF,0x00000000FFFF000000000000FFFF0000,0x0000FFFF000000000000FFFF00000000,0xFFFF000000000000FFFF000000000000
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "128"
                    distribution: block
                    gpus_on_node: "4"
                    gpus_per_node: "4"
                    gtids: 0,1,2,3
                    job_account: m3246_g
                    job_cpus_per_node: 128(x4)
                    job_end_time: "1784259873"
                    job_gid: "114650"
                    job_gpus: 0,1,2,3
                    job_group: mbenyas
                    job_id: "56002960"
                    job_licenses: cfs:1
                    job_name: interactive
                    job_nodelist: nid[001417,001420-001421,001424]
                    job_num_nodes: "4"
                    job_partition: urgent_gpu_ss11
                    job_qos: gpu_interactive
                    job_start_time: "1784245473"
                    job_uid: "114650"
                    job_user: mbenyas
                    jobid: "56002960"
                    labelio: "1"
                    launch_node_ipaddr: 128.55.66.91
                    localid: "0"
                    mpi_type: cray_shasta
                    nnodes: "4"
                    nodeid: "0"
                    nodelist: nid[001417,001420-001421,001424]
                    nprocs: "16"
                    ntasks: "16"
                    ntasks_per_node: "4"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "45691"
                    pty_win_col: "116"
                    pty_win_row: "24"
                    script_context: prolog_task
                    srun_comm_host: 128.55.66.91
                    srun_comm_port: "39523"
                    step_gpus: 0,1,2,3
                    step_id: "0"
                    step_launcher_port: "39523"
                    step_nodelist: nid[001417,001420-001421,001424]
                    step_num_nodes: "4"
                    step_num_tasks: "16"
                    step_resv_ports: 63002-63006
                    step_tasks_per_node: 4(x4)
                    stepid: "0"
                    stepmgr: nid001417
                    submit_dir: /global/cfs/cdirs/m3246/mbenyas/OmniLearned_distillation
                    submit_host: login15
                    task_pid: "1867197"
                    tasks_per_node: 4(x4)
                    topology_addr: global.group8.nid001417
                    topology_addr_pattern: switch.switch.node
                    umask: "0007"
                startedAt: "2026-07-16T23:46:33.470596Z"
                writerId: tni5vmvop1s2la55l839ib8lzwoi7ik6
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
                - 83
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
                - 83
            "3":
                - 13
                - 16
            "4": 3.12.13
            "5": 0.26.1
            "6": 5.8.0
            "12": 0.26.1
            "13": linux-x86_64
batch size:
    value: 128
distill:
    value: false
distill_T:
    value: 4
distill_alpha:
    value: 0.5
distill_beta:
    value: 0.5
epochs:
    value: 15
fine_tune:
    value: false
learning_rate:
    value: 1e-06
mode:
    value: classifier
size:
    value: large
