_wandb:
    value:
        cli_version: 0.26.1
        e:
            xp9tnq7wl37jt2jodxrzj69p056cvxbp:
                args:
                    - train
                    - -o
                    - /pscratch/sd/m/mbenyas/
                    - --save-tag
                    - fine_tune_qg_pretrain_l
                    - --pretrain-tag
                    - pretrain_l
                    - --fine-tune
                    - --dataset
                    - qg
                    - --mode
                    - classifier
                    - --num-classes
                    - "2"
                    - --path
                    - /global/cfs/cdirs/m4567/www/
                    - --size
                    - large
                    - --interaction
                    - --local-interaction
                    - --batch
                    - "128"
                    - --iterations
                    - "1000"
                    - --epoch
                    - "50"
                    - --lr
                    - "5e-5"
                    - --lr-factor
                    - "10"
                    - --wd
                    - "0.5"
                    - --num-workers
                    - "4"
                    - --wandb
                    - --resuming
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "134865870848"
                        used: "703463424"
                email: mbenyas@stanford.edu
                executable: /global/common/software/nersc9/pytorch/2.11.0/bin/python3.12
                git:
                    commit: 5dbfc9d9701993c492f317d5ae9ec968289056e5
                    remote: https://github.com/wamorkart/OmniLearned.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-d1bad154-fe9e-ae98-f2d7-2e1c8f305049
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-c111346b-445d-9cea-6705-80cbb8171397
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-48669bcd-2940-a83a-f400-d706ff087e5e
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-79fed957-0900-99e8-3208-258717f30232
                host: nid002061
                memory:
                    total: "269731741696"
                os: Linux-6.4.0-150600.23.103_15.0.25-cray_shasta_c-x86_64-with-glibc2.38
                program: /global/homes/m/mbenyas/.local/perlmutter/pytorch2.11.0/bin/omnilearned
                python: CPython 3.12.13
                root: /global/cfs/cdirs/m3246/mbenyas/OmniLearned_distillation
                slurm:
                    cluster_name: perlmutter
                    cpu_bind: quiet,mask_cpu:0x000000000000FFFF000000000000FFFF,0x00000000FFFF000000000000FFFF0000,0x0000FFFF000000000000FFFF00000000,0xFFFF000000000000FFFF000000000000
                    cpu_bind_list: 0x000000000000FFFF000000000000FFFF,0x00000000FFFF000000000000FFFF0000,0x0000FFFF000000000000FFFF00000000,0xFFFF000000000000FFFF000000000000
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "128"
                    distribution: block
                    gpus_on_node: "4"
                    gpus_per_node: "4"
                    gtids: 0,1,2,3
                    job_account: m3246_g
                    job_cpus_per_node: 128(x4)
                    job_end_time: "1784232971"
                    job_gid: "114650"
                    job_gpus: 0,1,2,3
                    job_group: mbenyas
                    job_id: "55982747"
                    job_licenses: cfs:1
                    job_name: interactive
                    job_nodelist: nid[002061,008212,008369,008637]
                    job_num_nodes: "4"
                    job_partition: urgent_gpu_ss11
                    job_qos: gpu_interactive
                    job_start_time: "1784218571"
                    job_uid: "114650"
                    job_user: mbenyas
                    jobid: "55982747"
                    labelio: "1"
                    launch_node_ipaddr: 128.55.68.22
                    localid: "0"
                    mpi_type: cray_shasta
                    nnodes: "4"
                    nodeid: "0"
                    nodelist: nid[002061,008212,008369,008637]
                    nprocs: "16"
                    ntasks: "16"
                    ntasks_per_node: "4"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "41781"
                    pty_win_col: "125"
                    pty_win_row: "17"
                    script_context: prolog_task
                    srun_comm_host: 128.55.68.22
                    srun_comm_port: "35519"
                    step_gpus: 0,1,2,3
                    step_id: "0"
                    step_launcher_port: "35519"
                    step_nodelist: nid[002061,008212,008369,008637]
                    step_num_nodes: "4"
                    step_num_tasks: "16"
                    step_resv_ports: 63002-63006
                    step_tasks_per_node: 4(x4)
                    stepid: "0"
                    stepmgr: nid002061
                    submit_dir: /global/cfs/cdirs/m3246/mbenyas/OmniLearned_distillation
                    submit_host: login08
                    task_pid: "1791601"
                    tasks_per_node: 4(x4)
                    topology_addr: global.group13.nid002061
                    topology_addr_pattern: switch.switch.node
                    umask: "0007"
                startedAt: "2026-07-16T16:55:38.536883Z"
                writerId: xp9tnq7wl37jt2jodxrzj69p056cvxbp
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
                - 83
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
                - 83
            "3":
                - 13
                - 16
            "4": 3.12.13
            "5": 0.26.1
            "6": 5.8.0
            "12": 0.26.1
            "13": linux-x86_64
batch size:
    value: 128
distill:
    value: false
distill_T:
    value: 4
distill_alpha:
    value: 0.5
distill_beta:
    value: 0.5
epochs:
    value: 50
fine_tune:
    value: true
learning_rate:
    value: 5e-05
mode:
    value: classifier
size:
    value: large
